spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.130/fastborrow?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.111
    port: 6379
server:
  servlet:
    context-path: /fastborrow
#  port: 8090
logging:
  level:
    com.myself.sbdiancan.dataobject.mapper: trace